version: "3.8"
name: map-stack

services:
  db:
    container_name: mysql-map
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_USER=MapUser
      - MYSQL_PASSWORD=map
      - MYSQL_ROOT_PASSWORD=map
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
  mongodb:
    container_name: mongodb-map
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=MapUser
      - MONGO_INITDB_ROOT_PASSWORD=map
    volumes:
      - mongodbdata:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=MapUser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=map
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  db:
    driver: local
  mongodbdata:
    driver: local
